name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, win, macos]
        arch: [x64, arm64]
        include:
          - os: linux
            platform: linux
            extension: ''
          - os: win
            platform: windows
            extension: '.exe'
          - os: macos
            platform: osx
            extension: ''
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Build single-file binary
        run: |
          rid="${{ matrix.os }}-${{ matrix.arch }}"
          output_dir="publish/${rid}"

          dotnet publish src/dnslg.csproj -c Release \
            -r $rid \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:PublishTrimmed=true \
            /p:IncludeNativeLibrariesForSelfExtract=true \
            -o $output_dir

          mv "$output_dir/dnslg${{ matrix.extension }}" "dnslg-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.extension }}"
        shell: bash

      - name: Upload binary to 'latest' GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
          files: dnslg-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.extension }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-dns-lists:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Upload dns source lists to 'latest' GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
          files: dns-source-lists/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}