name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, win, macos]
        arch: [x64, arm64]
        include:
          - os: linux
            rid_prefix: linux
            extension: ''
          - os: win
            rid_prefix: win
            extension: '.exe'
          - os: macos
            rid_prefix: osx
            extension: ''
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Build single-file binary
        run: |
          rid="${{ matrix.rid_prefix }}-${{ matrix.arch }}"
          output_dir="publish/${rid}"
          dotnet publish src/dnslg.csproj -c Release \
            -r $rid \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:PublishTrimmed=true \
            /p:IncludeNativeLibrariesForSelfExtract=true \
            -o $output_dir
          mv "$output_dir/dnslg${{ matrix.extension }}" "dnslg-${rid}${{ matrix.extension }}"
        shell: bash

      - name: Copy everything to release directory
        run: |
          mkdir -p release-files
          cp dns-source-lists/* release-files/
          cp dnslg-* release-files/
        shell: bash

      - name: Upload to 'latest' GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
          files: release-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
