name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - name: Delete existing release
        run: gh release delete latest --repo ${{ github.repository }} --cleanup-tag --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    needs: clean-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Create release
        run: |
          gh release create latest \
            --title "Latest Build" \
            --notes "Automated release" \
            --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload DNS source lists to release
        run: |
          for file in dns-source-lists/*; do
            gh release upload latest "$file" --repo ${{ github.repository }}
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-upload:
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, win, macos]
        arch: [x64, arm64]
        include:
          - os: linux
            rid: linux
            platform: linux
            extension: ''
          - os: win
            rid: win
            platform: windows
            extension: '.exe'
          - os: macos
            rid: osx
            platform: osx
            extension: ''
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Build single-file binary
        run: |
          rid="${{ matrix.rid }}-${{ matrix.arch }}"
          output_dir="publish/${rid}"

          dotnet publish src/dnslg.csproj -c Release \
            -r $rid \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:PublishTrimmed=true \
            /p:IncludeNativeLibrariesForSelfExtract=true \
            -o $output_dir

          mv "$output_dir/dnslg${{ matrix.extension }}" "dnslg-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.extension }}"
        shell: bash

      - name: Upload binary to release
        run: |
          gh release upload latest "dnslg-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.extension }}" --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}